### PR TITLE
GitHub action tests fix

### LINKED ISSUE #866: Failing tests issue in github actions

### PR DESCRIPTION
**Pull request by aserkes**
- Set maven.test.failure.ignore to false in github actions
- Prepare surefire reports even if maven build is failed
- Fix SchemaTest
- Disable failed tests

Fixes #866

### CODE REVIEW

**Review by romain-grecourt — APPROVED** [review]

**Review by romain-grecourt — COMMENTED** [review]
Can you create issues to track the disabled tests ?

**Comment by aserkes** [comment]
> Can you create issues to track the disabled tests ?
The issue was created - #868

**Comment by romain-grecourt** [comment]
> > Can you create issues to track the disabled tests ?
> > The issue was created - #868

That issue does not list the tests that need work.
We should either file separate issues for each set of tests that need to be fixed, or have a task list in the issue you created.

**Comment by tvallin** [comment]
What is the difference between `build.sh` and `github-build.sh` ? It looks like it is doing the same thing, or did I miss something ?

**Comment by aserkes** [comment]
> What is the difference between `build.sh` and `github-build.sh` ? It looks like it is doing the same thing, or did I miss something ?

-Dmaven.test.failure.ignore=false

**Comment by aserkes** [comment]
> > > Can you create issues to track the disabled tests ?
> > > The issue was created - #868
> 
> That issue does not list the tests that need work. We should either file separate issues for each set of tests that need to be fixed, or have a task list in the issue you created.

I have added the list of the failed tests to the description of the issue #868

**Pull request merged**
